{% set version = "25.06.0" %}
{% set number = 0 %}
{% set min_cutlass_version = "3.9.0.*" %}

{% set major_version = version.split(".")[0] %}
{% set minor_version = version.split(".")[1] %}

package:
  name: mathdx
  version: {{ version }}

source:
  - url: https://developer.download.nvidia.com/compute/cuFFTDx/redist/cuFFTDx/nvidia-mathdx-{{ version }}.tar.gz
    sha256: 3831cc1ee33a3c7d227eb7f30d7969796e14fec0445bac90f25116f5d6cb5b3a

build:
  number: {{ number }}
  noarch: generic
  # cuda is only for tests, so we don't want to build multiple variants
  skip: true  # [(not linux) or (not (cuda_compiler_version or "").startswith("12"))]
  script:
    - cp -vr $SRC_DIR/nvidia/mathdx/{{ major_version }}.{{ minor_version }}/include/* $PREFIX/include/  # [linux]
    - cp -vr $SRC_DIR/nvidia/mathdx/{{ major_version }}.{{ minor_version }}/lib/* $PREFIX/lib/          # [linux]
    - mv -v $SRC_DIR/nvidia/mathdx/{{ major_version }}.{{ minor_version }}/src $PREFIX/          # [linux]
    - cp $SRC_DIR/nvidia/mathdx/{{ major_version }}.{{ minor_version }}/LICENSE.txt $SRC_DIR/          # [linux]
    - sed -i -E 's|get_filename_component\(PACKAGE_PREFIX_DIR.*|set\(PACKAGE_PREFIX_DIR "/opt/anaconda1anaconda2anaconda3"\)|g' $PREFIX/lib/cmake/*/*dx-config.cmake  # [linux]
    - sed -i -E 's|\$\{PACKAGE_PREFIX_DIR\}/external/cutlass|/opt/anaconda1anaconda2anaconda3|g' $PREFIX/lib/cmake/*/*dx-config.cmake  # [linux]
    - check-glibc "$PREFIX"/lib*/*.so.* "$PREFIX"/bin/* "$PREFIX"/targets/*/lib*/*.so.* "$PREFIX"/targets/*/bin/*  # [linux]

requirements:
  build:
    - cf-nvidia-tools 1  # [linux]
  host:
    - cutlass {{ min_cutlass_version }}
  run:
    - __unix
    - {{ pin_compatible("cutlass", max_pin="x") }}
  run_constrained:
    - cuda-version >=11.0.*,<13.a0  # mathdx supports both CUDA majors

test:
  files:
    - test
  requires:
    - tree  # [linux]
    - {{ compiler("c") }}  # [linux]
    - {{ compiler("cxx") }}  # [linux]
    - {{ stdlib("c") }}  # [linux]
    - {{ compiler("cuda") }}  # [linux]
    - cmake  # [linux]
    - ninja  # [linux]
    # Testing that the minimal supported version is correct
    - cutlass {{ min_cutlass_version }}
    - libcurand-dev
  commands:
    - test -f $PREFIX/include/cufftdx.hpp                   # [linux]
    - test -f $PREFIX/include/cublasdx.hpp                  # [linux]
    - test -f $PREFIX/lib/cmake/mathdx/mathdx-config.cmake  # [linux]
    - test -d $PREFIX/include/cufftdx                       # [linux]
    - test -d $PREFIX/include/cublasdx                      # [linux]
    - tree $PREFIX/include/                                 # [linux]
    - cmake ${CMAKE_ARGS} -GNinja test                      # [linux]
    - cmake --build .                                       # [linux]


about:
  home: https://developer.nvidia.com/mathdx
  license: LicenseRef-MathDx-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cufftdx/license.html
  license_file: LICENSE.txt
  summary: "NVIDIA MathDx device libraries"
  description: |
    NVIDIA MathDx currently contains cuBLASDx, cuFFTDx, cuSolverDx, cuRANDDx, and nvCOMPDx.
  doc_url: https://docs.nvidia.com/cuda/cufftdx/

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - leofang
