{% set version = "24.08.0" %}
{% set number = 2 %}
{% set min_cutlass_version = "3.5.1" %}

{% set major_version = version.split(".")[0] %}
{% set minor_version = version.split(".")[1] %}

package:
  name: mathdx
  version: {{ version }}

source:
  - url: https://developer.download.nvidia.com/compute/cuFFTDx/redist/cuFFTDx/nvidia-mathdx-{{ version }}.tar.gz
    sha256: 66e4a0a1d15969c6b099e15e6f89a89a378b630b8ec7dca18f3e573bf403e0a2

build:
  number: {{ number }}
  noarch: generic
  # cuda is only for tests, so we don't want to build multiple variants
  skip: true  # [(not linux) or (not (cuda_compiler_version or "").startswith("12"))]
  script:
    - cp -r $SRC_DIR/nvidia/mathdx/{{ major_version }}.{{ minor_version }}/include/* $PREFIX/include/  # [linux]
    - cp -r $SRC_DIR/nvidia/mathdx/{{ major_version }}.{{ minor_version }}/lib/* $PREFIX/lib/          # [linux]
    - cp $SRC_DIR/nvidia/mathdx/{{ major_version }}.{{ minor_version }}/LICENSE.txt $SRC_DIR/          # [linux]
    - sed -i -E 's/(set_and_check\(mathdx_INCLUDE_DIRS?).*/\1 "${CMAKE_CURRENT_LIST_DIR}\/..\/..\/..\/include")/' $PREFIX/lib/cmake/mathdx/mathdx-config.cmake  # [linux]
    - sed -i -E 's/(set_and_check\(cublasdx_INCLUDE_DIRS?).*/\1 "${CMAKE_CURRENT_LIST_DIR}\/..\/..\/..\/include")/' $PREFIX/include/cublasdx/lib/cmake/cublasdx/cublasdx-config.cmake  # [linux]
    - sed -i -E 's/(INTERFACE_INCLUDE_DIRECTORIES).*/\1 "${CMAKE_CURRENT_LIST_DIR}\/..\/..\/..\/include"/' $PREFIX/include/cublasdx/lib/cmake/cublasdx/cublasdx-targets.cmake  # [linux]
    - sed -i -E 's/(INTERFACE_INCLUDE_DIRECTORIES).*/\1 "${CMAKE_CURRENT_LIST_DIR}\/..\/..\/..\/include"/' $PREFIX/lib/cmake/mathdx/mathdx-targets.cmake  # [linux]
    - sed -i -E '/set_and_check\(mathdx_inc_CUTLASS_ROOT/d' $PREFIX/lib/cmake/mathdx/mathdx-config.cmake  # [linux]
    - sed -i -E '/set_and_check\(mathdx_inc_CUTLASS_INCLUDE_DIR/d' $PREFIX/lib/cmake/mathdx/mathdx-config.cmake  # [linux]

requirements:
  build:
  host:
    - cutlass {{ min_cutlass_version }}
  run:
    - __unix
    - {{ pin_compatible("cutlass", max_pin="x") }}
  run_constrained:
    - cuda-version >=11.0.*,<13.a0  # mathdx supports both CUDA majors

test:
  files:
    - test
  requires:
    - tree  # [linux]
    - {{ compiler("c") }}  # [linux]
    - {{ compiler("cxx") }}  # [linux]
    - {{ stdlib("c") }}  # [linux]
    - {{ compiler("cuda") }}  # [linux]
    - cmake  # [linux]
    - ninja  # [linux]
    # Testing that the minimal supported version is correct
    - cutlass {{ min_cutlass_version }}
  commands:
    - test -f $PREFIX/include/cufftdx.hpp                   # [linux]
    - test -f $PREFIX/include/cublasdx.hpp                  # [linux]
    - test -f $PREFIX/lib/cmake/mathdx/mathdx-config.cmake  # [linux]
    - test -d $PREFIX/include/cufftdx                       # [linux]
    - test -d $PREFIX/include/cublasdx                      # [linux]
    - tree $PREFIX/include/                                 # [linux]
    - cmake ${CMAKE_ARGS} -GNinja test                      # [linux]
    - cmake --build .                                       # [linux]


about:
  home: https://developer.nvidia.com/mathdx
  license: LicenseRef-MathDx-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cufftdx/license.html
  license_file: LICENSE.txt
  summary: "NVIDIA MathDx device libraries"
  description: |
    NVIDIA MathDx currently contains cuFFTDx and cuBLASDx.
  doc_url: https://docs.nvidia.com/cuda/cufftdx/

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - leofang
